import "./css/style.css";

import { Inter } from "next/font/google";
import Theme from "./theme-provider";
import AppProvider from "./app-provider";
import Sidebar from "@/components/ui/sidebar";
import Header from "@/components/ui/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} font-inter antialiased bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400`}
      >
        <Theme>
          <AppProvider>
            <div className="flex h-[100dvh] overflow-hidden">
              <Sidebar />
              <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
                <Header />

                <main className="grow [&>*:first-child]:scroll-mt-16">
                  {children}
                </main>
              </div>
            </div>
          </AppProvider>
        </Theme>
      </body>
    </html>
  );
}
